// Register local selectors separately from exact authenticated gateway routes.
import type { Api, Model } from "@oh-my-pi/pi-ai";
import { streamSimple } from "@oh-my-pi/pi-ai";
import { getBundledModels } from "@oh-my-pi/pi-catalog/models";
import type { buildModel as BuildNativeModel } from "@oh-my-pi/pi-catalog/build";
import type { ExtensionAPI, ProviderConfig, ProviderModelConfig } from "@oh-my-pi/pi-coding-agent";

import { ALLOWED_APIS, baseUrlFor } from "./compat.ts";
import type { CustomProviderConfig, CustomProviderModelConfig, ProxyConfig } from "./config.ts";
import { resolveConfigValue } from "./config.ts";
import type { Discovery, DiscoveryModelEntry } from "./fetch-models.ts";
import { log } from "./log.ts";
import { createLatencyDiagnostics } from "./latency.ts";

type GatewayFetch = (input: string | URL | Request, init?: RequestInit) => Promise<Response>;
type GatewayStreamOptions = NonNullable<Parameters<typeof streamSimple>[2]> & {
	fetch?: GatewayFetch;
	maxInFlightRequests?: Record<string, number>;
};

const appliedProviderNames = new WeakMap<ExtensionAPI, Set<string>>();

type NativeModelBuilder = typeof BuildNativeModel;
let nativeModelBuilder: NativeModelBuilder | undefined;

/** Plugin dependency readiness, not a custom host capability or version marker. */
export async function requireGatewayTransport(): Promise<NativeModelBuilder> {
	if (nativeModelBuilder) return nativeModelBuilder;
	// Static loading would abort extension initialization on an incomplete
	// plugin install, before we can refuse credential resolution actionably.
	try {
		const catalog = await import("@oh-my-pi/pi-catalog/build");
		if (typeof catalog.buildModel !== "function") throw new Error("missing builder");
		nativeModelBuilder = catalog.buildModel;
		return nativeModelBuilder;
	} catch {
		throw new Error(
			"AI Gateway transport unavailable: reinstall this plugin with its pinned @oh-my-pi/pi-catalog@18.2.0 dependency and restart standard OMP. No gateway credentials were resolved and no providers were registered.",
		);
	}
}

// Availability marker only. Never expose the gateway credential to the host's
// provider-wide lookup, which may also serve refreshed first-party models.
const GATEWAY_AUTH_MARKER = "agp-plugin-managed-not-a-credential";

export interface ApplyReport {
	registered: Array<{ provider: string; modelCount: number; api: Api }>;
	skipped: Array<{ provider: string; reason: string }>;
}

/** OMP's explicit-state contract; upstream Pi's peer types still require numbers. */
export interface GatewayModelConfig extends CustomProviderModelConfig {
	name: string;
	api: Api;
	metadataState: DiscoveryModelEntry["metadataState"];
	priceState: DiscoveryModelEntry["priceState"];
}

/** Server namespaces are authoritative for connector-backed groups. */
export function registrationConfig(cfg: ProxyConfig, discovery: Discovery): ProxyConfig {
	if (!cfg.registerAll) return cfg;
	const builtinProviders = Object.fromEntries(
		discovery.builtinProviders.map((p) => [
			p.name,
			{
				...cfg.builtinProviders[p.name],
				enabled: true,
				models: p.models.map((m) => m.id),
			},
		]),
	);
	const customProviders: Record<string, CustomProviderConfig> = {};
	// A matching wire ID is not proof that an explicit group was generated by
	// AGP. Preserve every explicit group; discovery adds its stable namespace
	// separately, without mutating or silently discarding operator settings.
	for (const [name, provider] of Object.entries(cfg.customProviders)) {
		customProviders[name] = { ...provider, models: [...provider.models] };
	}
	for (const m of discovery.customPool) {
		const explicitOwner = !m.providerId
			? Object.entries(cfg.customProviders).find(([, provider]) =>
					provider.models.some((entry) => entry.id === m.id),
				)?.[0]
			: undefined;
		const name =
			explicitOwner ?? (m.providerId ? m.suggestedProvider : registerAllSlug(m.suggestedProvider));
		if (m.providerId && !/^[a-z0-9][a-z0-9._-]*$/.test(name))
			throw new Error(`Invalid gateway provider namespace for ${m.id}`);
		const explicit = cfg.customProviders[name];
		const group = (customProviders[name] ??= { api: explicit?.api ?? m.api, models: [] });
		if (group.api !== m.api) throw new Error(`Conflicting API families for provider ${name}`);
		if (!group.models.some((entry) => entry.id === m.id)) {
			group.models.push({ ...explicit?.models.find((entry) => entry.id === m.id), id: m.id });
		}
	}
	return { ...cfg, builtinProviders, customProviders };
}

/** Manual overrides > explicit model settings > server > genuine local catalog. */
export function mergeModelMetadata(
	entry: DiscoveryModelEntry,
	configured: CustomProviderModelConfig,
	override: Partial<CustomProviderModelConfig>,
	api: Api,
	catalog?: Partial<Pick<Model<Api>, "reasoning" | "input" | "contextWindow" | "maxTokens">>,
): GatewayModelConfig {
	const merged: GatewayModelConfig = {
		id: entry.selectorId ?? entry.id,
		name: override.name ?? configured.name ?? entry.name,
		api,
		metadataState: entry.metadataState,
		priceState: "unknown",
	};
	let manualMetadata = false;
	for (const key of ["reasoning", "input", "contextWindow", "maxTokens"] as const) {
		const value = override[key] ?? configured[key] ?? entry[key] ?? catalog?.[key];
		if (value !== undefined && value !== null) Object.assign(merged, { [key]: value });
		if (override[key] !== undefined || configured[key] !== undefined) manualMetadata = true;
	}
	if (manualMetadata) merged.metadataState = "override";
	else if (
		merged.metadataState === "unknown" &&
		catalog &&
		[merged.reasoning, merged.input, merged.contextWindow, merged.maxTokens].some(
			(v) => v !== undefined,
		)
	)
		merged.metadataState = "catalog";
	// Gateway prices are the active AGP snapshot, not a bundled upstream tariff.
	const cost: NonNullable<CustomProviderModelConfig["cost"]> = {};
	for (const key of ["input", "output", "cacheRead", "cacheWrite"] as const) {
		const value = override.cost?.[key] ?? configured.cost?.[key] ?? entry.cost?.[key];
		if (value !== undefined) {
			if (!Number.isFinite(value) || value < 0)
				throw new Error(`Invalid ${key} price for ${entry.id}`);
			cost[key] = value;
		}
	}
	if (Object.keys(cost).length) {
		merged.cost = cost;
		merged.priceState = cost.input !== undefined && cost.output !== undefined ? "known" : "partial";
	}
	for (const key of ["contextWindow", "maxTokens"] as const) {
		const value = merged[key];
		if (value !== undefined && (!Number.isSafeInteger(value) || value <= 0))
			throw new Error(`Invalid ${key} for ${entry.id}`);
	}
	return merged;
}

export async function applyAll(
	pi: ExtensionAPI,
	cfg: ProxyConfig,
	discovery: Discovery,
): Promise<ApplyReport> {
	const buildModel = await requireGatewayTransport();
	const report: ApplyReport = { registered: [], skipped: [] };
	const resolvedKey = resolveConfigValue(cfg.proxy.apiKey);
	if (!resolvedKey) {
		log.warn("proxy apiKey is empty — provider registration skipped");
		return report;
	}
	cfg = registrationConfig(cfg, discovery);
	const registeredNames = new Set<string>();
	const ownedNames = appliedProviderNames.get(pi) ?? new Set<string>();
	appliedProviderNames.set(pi, ownedNames);
	const register = (
		name: string,
		api: Api,
		models: GatewayModelConfig[],
		routes: Map<string, string>,
	) => {
		const bridgeAPI = `agp:${name}:${api}`;
		const gatewayBaseUrl = baseUrlFor(api, cfg.proxy.endpoint);
		const endpointSuffix =
			api === "anthropic-messages"
				? "/v1/messages"
				: api === "openai-responses"
					? "/responses"
					: "/chat/completions";
		const gatewayRequestURL = new URL(gatewayBaseUrl.replace(/\/+$/, "") + endpointSuffix);
		const config: ProviderConfig & { fetchDynamicModels(): Promise<ProviderModelConfig[]> } = {
			baseUrl: gatewayBaseUrl,
			apiKey: GATEWAY_AUTH_MARKER,
			authHeader: false,
			api: bridgeAPI,
			// Discovery truth is retained by the plugin. Stock hosts may supply
			// runtime defaults for omitted metadata; the plugin UI stays explicit.
			models: models.map((m) => {
				const unavailable = [
					...(m.contextWindow === undefined ? ["context unknown"] : []),
					...(m.maxTokens === undefined ? ["output limit unknown"] : []),
					...(m.priceState !== "known" ? [`price ${m.priceState}`] : []),
				];
				return {
					...m,
					api: bridgeAPI,
					name: unavailable.length ? `${m.name} [${unavailable.join("; ")}]` : m.name,
				};
			}) as unknown as ProviderModelConfig[],
			// Stock OMP excludes its built-in discovery only when an extension
			// owns a dynamic model manager. Static models alone do not own a namespace.
			async fetchDynamicModels() {
				return config.models ?? [];
			},
			streamSimple(model, context, options) {
				if (
					model.provider !== name ||
					model.api !== bridgeAPI ||
					model.baseUrl !== gatewayBaseUrl
				) {
					throw new Error(
						"Gateway model transport identity does not match its registered provider",
					);
				}
				const wireId = routes.get(model.id);
				if (!wireId) throw new Error(`Unknown gateway selector ${name}/${model.id}`);
				const diagnostics = createLatencyDiagnostics();
				const headers = new Headers(options?.headers);
				const transportHeaders = new Headers(model.headers);
				headers.delete("authorization");
				headers.delete("x-api-key");
				headers.delete("api-key");
				if (
					options?.sessionId &&
					!headers.has("x-session-id") &&
					!transportHeaders.has("x-session-id")
				) {
					headers.set("x-session-id", options.sessionId);
				}
				// OpenCode Go routes by its own conversation header; without it the
				// upstream rejects the request even when the gateway session id is
				// present. A caller-set value always wins.
				if (
					options?.sessionId &&
					!headers.has("x-opencode-session") &&
					!transportHeaders.has("x-opencode-session")
				) {
					headers.set("x-opencode-session", options.sessionId);
				}
				// Dispatch through the supported root API, with the real built-in
				// family restored. Keeping agp:* here would recurse into this hook.
				transportHeaders.delete("authorization");
				transportHeaders.delete("x-api-key");
				transportHeaders.delete("api-key");
				const nativeModel = buildModel({
					...model,
					api,
					baseUrl: gatewayBaseUrl,
					headers: Object.fromEntries(transportHeaders),
					compat: (model as typeof model & { compatConfig?: unknown }).compatConfig,
				} as Parameters<typeof buildModel>[0]);
				const transportModel = {
					...nativeModel,
					cost: model.cost,
					contextWindow: model.contextWindow,
					maxTokens: model.maxTokens,
				} as unknown as Parameters<typeof streamSimple>[0];
				// Do not delegate to options.fetch: the outer host wraps it for
				// request debugging and may route it independently. Native transport
				// options (signal, CA/proxy init) already reach this final boundary.
				const send = globalThis.fetch;
				const gatewayFetch: GatewayFetch = async (input, init) => {
					const target = new URL(input instanceof Request ? input.url : String(input));
					if (target.href !== gatewayRequestURL.href || target.username || target.password) {
						throw new Error("Gateway transport rejected an endpoint outside its registered route");
					}
					// Reassert credentials only after validating the final SDK URL. Native
					// environment/auth defaults cannot replace the configured gateway key.
					const requestHeaders = new Headers(
						init?.headers ?? (input instanceof Request ? input.headers : undefined),
					);
					requestHeaders.set("authorization", `Bearer ${resolvedKey}`);
					requestHeaders.delete("x-api-key");
					requestHeaders.delete("api-key");
					if (diagnostics) requestHeaders.set("x-agp-trace-id", diagnostics.traceId);
					const attempt = diagnostics?.dispatch();
					const response = await send(input, {
						...init,
						headers: requestHeaders,
						redirect: "error",
					});
					diagnostics?.headers(response, attempt!);
					return response;
				};
				const transportOptions: GatewayStreamOptions = {
					...options,
					apiKey: GATEWAY_AUTH_MARKER,
					// The outer custom API already owns the provider permit. An empty
					// override disables only this nested acquisition (undefined would
					// fall back to the host's configured cap and deadlock at cap=1).
					maxInFlightRequests: {},
					fetch: gatewayFetch,
					headers: Object.fromEntries(headers),
					onPayload: async (payload, sdkModel) => {
						const next = (await options?.onPayload?.(payload, sdkModel)) ?? payload;
						if (!next || typeof next !== "object" || Array.isArray(next))
							throw new Error("Invalid gateway inference payload");
						return { ...next, model: wireId };
					},
				};
				if (diagnostics) {
					const nativeOptions = transportOptions as GatewayStreamOptions & {
						onSseEvent?: (...args: unknown[]) => void;
					};
					const onSseEvent = nativeOptions.onSseEvent;
					nativeOptions.onSseEvent = (...args) => {
						diagnostics.firstSse();
						onSseEvent?.(...args);
					};
					diagnostics.prepared();
				}
				try {
					const stream = streamSimple(transportModel, context, transportOptions);
					return diagnostics ? diagnostics.observe(stream) : stream;
				} catch (error) {
					diagnostics?.failed();
					throw error;
				}
			},
		};
		pi.registerProvider(name, config);
		registeredNames.add(name);
		ownedNames.add(name);
		report.registered.push({ provider: name, modelCount: models.length, api });
	};

	for (const [name, provider] of Object.entries(cfg.builtinProviders)) {
		if (!provider?.enabled) {
			report.skipped.push({ provider: name, reason: "disabled" });
			continue;
		}
		const fromServer = discovery.builtinProviders.find((p) => p.name === name);
		const api = provider.apiOverride ?? fromServer?.api;
		if (!api || !ALLOWED_APIS.has(api)) {
			report.skipped.push({ provider: name, reason: "no supported API in discovery" });
			continue;
		}
		let catalog: Model<Api>[] = [];
		try {
			catalog = getBundledModels(name as Parameters<typeof getBundledModels>[0]);
		} catch {
			/* no local catalog */
		}
		const models: GatewayModelConfig[] = [];
		const routes = new Map<string, string>();
		for (const id of provider.models ?? []) {
			const entry = fromServer?.models.find((m) => m.id === id);
			if (!entry) continue;
			const model = mergeModelMetadata(
				entry,
				{ id },
				cfg.overrides[id] ?? {},
				api,
				entry.providerId ? undefined : catalog.find((m) => m.id === id),
			);
			addRoute(name, entry, model.id, routes);
			models.push(model);
		}
		register(name, api, models, routes);
	}

	const byId = new Map(discovery.customPool.map((m) => [m.id, m]));
	for (const [name, provider] of Object.entries(cfg.customProviders)) {
		if (!ALLOWED_APIS.has(provider.api)) {
			report.skipped.push({ provider: name, reason: `api "${provider.api}" not in allowlist` });
			continue;
		}
		const models: GatewayModelConfig[] = [];
		const routes = new Map<string, string>();
		for (const configured of provider.models) {
			const entry = byId.get(configured.id);
			if (!entry) continue;
			if (entry.api !== provider.api)
				throw new Error(`Model ${entry.id} requires ${entry.api}, not ${provider.api}`);
			const model = mergeModelMetadata(
				entry,
				configured,
				cfg.overrides[entry.id] ?? {},
				provider.api,
			);
			addRoute(name, entry, model.id, routes);
			models.push(model);
		}
		register(name, provider.api, models, routes);
	}
	for (const name of ownedNames) {
		if (!registeredNames.has(name)) pi.unregisterProvider(name);
	}
	appliedProviderNames.set(pi, registeredNames);
	log.info(
		`applyAll: registered ${report.registered.length} providers, skipped ${report.skipped.length}`,
	);
	return report;
}

function addRoute(
	name: string,
	entry: DiscoveryModelEntry,
	selector: string,
	routes: Map<string, string>,
): void {
	const wireId = entry.wireId ?? entry.id;
	if (entry.providerId && (!wireId.includes("/") || !entry.selectorId || selector.includes("/")))
		throw new Error(`Invalid gateway route: ${entry.id}`);
	if (routes.has(selector)) throw new Error(`Ambiguous selector ${name}/${selector}`);
	routes.set(selector, wireId);
}

/** Legacy display-oriented names are folded into safe provider slugs. */
export function registerAllSlug(suggested: string): string {
	const slug = suggested
		.trim()
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "");
	return slug || "pool";
}
