// Register local selectors separately from exact authenticated gateway routes.
import type { Api } from "@earendil-works/pi-ai";
import { getModels, streamSimple } from "@earendil-works/pi-ai";
import * as PiAI from "@earendil-works/pi-ai";
import type { ExtensionAPI, ProviderConfig, ProviderModelConfig } from "@earendil-works/pi-coding-agent";

import { ALLOWED_APIS, baseUrlFor } from "./compat.ts";
import type { CustomProviderConfig, CustomProviderModelConfig, ProxyConfig } from "./config.ts";
import { resolveConfigValue } from "./config.ts";
import type { Discovery, DiscoveryModelEntry } from "./fetch-models.ts";
import { log } from "./log.ts";


const appliedProviderNames = new WeakMap<ExtensionAPI, Set<string>>();

const hostModels = PiAI as typeof PiAI & {
	toModelSpec?: (model: Parameters<typeof streamSimple>[0]) => Record<string, unknown>;
	buildModel?: (spec: Record<string, unknown>) => Parameters<typeof streamSimple>[0];
};
export interface ApplyReport {
	registered: Array<{ provider: string; modelCount: number; api: Api }>;
	skipped: Array<{ provider: string; reason: string }>;
}

/** OMP's explicit-state contract; upstream Pi's peer types still require numbers. */
export interface GatewayModelConfig extends CustomProviderModelConfig {
	name: string;
	api: Api;
	metadataState: DiscoveryModelEntry["metadataState"];
	priceState: DiscoveryModelEntry["priceState"];
}

/** Server namespaces are authoritative for connector-backed groups. */
export function registrationConfig(cfg: ProxyConfig, discovery: Discovery): ProxyConfig {
	if (!cfg.registerAll) return cfg;
	const builtinProviders = Object.fromEntries(discovery.builtinProviders.map((p) => [p.name, {
		...cfg.builtinProviders[p.name], enabled: true, models: p.models.map((m) => m.id),
	}]));
	const customProviders: Record<string, CustomProviderConfig> = {};
	// A matching wire ID is not proof that an explicit group was generated by
	// AGP. Preserve every explicit group; discovery adds its stable namespace
	// separately, without mutating or silently discarding operator settings.
	for (const [name, provider] of Object.entries(cfg.customProviders)) {
		customProviders[name] = { ...provider, models: [...provider.models] };
	}
	for (const m of discovery.customPool) {
		const explicitOwner = !m.providerId
			? Object.entries(cfg.customProviders).find(([, provider]) => provider.models.some((entry) => entry.id === m.id))?.[0]
			: undefined;
		const name = explicitOwner ?? (m.providerId ? m.suggestedProvider : registerAllSlug(m.suggestedProvider));
		if (m.providerId && !/^[a-z0-9][a-z0-9._-]*$/.test(name)) throw new Error(`Invalid gateway provider namespace for ${m.id}`);
		const explicit = cfg.customProviders[name];
		const group = customProviders[name] ??= { api: explicit?.api ?? m.api, models: [] };
		if (group.api !== m.api) throw new Error(`Conflicting API families for provider ${name}`);
		if (!group.models.some((entry) => entry.id === m.id)) {
			group.models.push({ ...explicit?.models.find((entry) => entry.id === m.id), id: m.id });
		}
	}
	return { ...cfg, builtinProviders, customProviders };
}

/** Manual overrides > explicit model settings > server > genuine local catalog. */
export function mergeModelMetadata(
	entry: DiscoveryModelEntry,
	configured: CustomProviderModelConfig,
	override: Partial<CustomProviderModelConfig>,
	api: Api,
	catalog?: Partial<CustomProviderModelConfig>,
): GatewayModelConfig {
	const merged: GatewayModelConfig = {
		id: entry.selectorId ?? entry.id,
		name: override.name ?? configured.name ?? entry.name,
		api,
		metadataState: entry.metadataState,
		priceState: "unknown",
	};
	let manualMetadata = false;
	for (const key of ["reasoning", "input", "contextWindow", "maxTokens"] as const) {
		const value = override[key] ?? configured[key] ?? entry[key] ?? catalog?.[key];
		if (value !== undefined) Object.assign(merged, { [key]: value });
		if (override[key] !== undefined || configured[key] !== undefined) manualMetadata = true;
	}
	if (manualMetadata) merged.metadataState = "override";
	else if (merged.metadataState === "unknown" && catalog && [merged.reasoning, merged.input, merged.contextWindow, merged.maxTokens].some((v) => v !== undefined)) merged.metadataState = "catalog";
	// Gateway prices are the active AGP snapshot, not a bundled upstream tariff.
	const cost: NonNullable<CustomProviderModelConfig["cost"]> = {};
	for (const key of ["input", "output", "cacheRead", "cacheWrite"] as const) {
		const value = override.cost?.[key] ?? configured.cost?.[key] ?? entry.cost?.[key];
		if (value !== undefined) {
			if (!Number.isFinite(value) || value < 0) throw new Error(`Invalid ${key} price for ${entry.id}`);
			cost[key] = value;
		}
	}
	if (Object.keys(cost).length) {
		merged.cost = cost;
		merged.priceState = cost.input !== undefined && cost.output !== undefined ? "known" : "partial";
	}
	for (const key of ["contextWindow", "maxTokens"] as const) {
		const value = merged[key];
		if (value !== undefined && (!Number.isSafeInteger(value) || value <= 0)) throw new Error(`Invalid ${key} for ${entry.id}`);
	}
	return merged;
}

export async function applyAll(pi: ExtensionAPI, cfg: ProxyConfig, discovery: Discovery): Promise<ApplyReport> {
	const report: ApplyReport = { registered: [], skipped: [] };
	const resolvedKey = resolveConfigValue(cfg.proxy.apiKey);
	if (!resolvedKey) {
		log.warn("proxy apiKey is empty — provider registration skipped");
		return report;
	}
	cfg = registrationConfig(cfg, discovery);
	const registeredNames = new Set<string>();
	const ownedNames = appliedProviderNames.get(pi) ?? new Set<string>();
	appliedProviderNames.set(pi, ownedNames);
	const register = (name: string, api: Api, models: GatewayModelConfig[], routes: Map<string, string>) => {
		const bridgeAPI = `agp:${name}:${api}`;
		const config: ProviderConfig = {
			baseUrl: baseUrlFor(api, cfg.proxy.endpoint),
			apiKey: resolvedKey,
			authHeader: true,
			api: bridgeAPI,
			// Explicit metadata states are understood by OMP's host contract. The
			// published upstream peer type has not yet adopted optional metadata.
			models: models.map((m) => ({ ...m, api: bridgeAPI })) as unknown as ProviderModelConfig[],
			streamSimple(model, context, options) {
				const wireId = routes.get(model.id);
				if (!wireId) throw new Error(`Unknown gateway selector ${name}/${model.id}`);
				const headers = new Headers(options?.headers);
				if (options?.sessionId && !headers.has("x-session-id") && !new Headers(model.headers).has("x-session-id")) {
					headers.set("x-session-id", options.sessionId);
				}
				// Dispatch through the supported root API, with the real built-in
				// family restored. Keeping agp:* here would recurse into this hook.
				const transportModel = hostModels.buildModel && hostModels.toModelSpec
					? hostModels.buildModel({ ...hostModels.toModelSpec(model), api })
					: { ...model, api };
				return streamSimple(transportModel, context, {
					...options,
					headers: Object.fromEntries(headers),
					onPayload: async (payload, sdkModel) => {
						const next = await options?.onPayload?.(payload, sdkModel) ?? payload;
						if (!next || typeof next !== "object" || Array.isArray(next)) throw new Error("Invalid gateway inference payload");
						return { ...next, model: wireId };
					},
				});
			},
		};
		pi.registerProvider(name, config);
		registeredNames.add(name);
		ownedNames.add(name);
		report.registered.push({ provider: name, modelCount: models.length, api });
	};

	for (const [name, provider] of Object.entries(cfg.builtinProviders)) {
		if (!provider?.enabled) {
			report.skipped.push({ provider: name, reason: "disabled" });
			continue;
		}
		const fromServer = discovery.builtinProviders.find((p) => p.name === name);
		const api = provider.apiOverride ?? fromServer?.api;
		if (!api || !ALLOWED_APIS.has(api)) {
			report.skipped.push({ provider: name, reason: "no supported API in discovery" });
			continue;
		}
		let catalog: ReadonlyArray<Partial<CustomProviderModelConfig> & { id: string }> = [];
		try { catalog = getModels(name as Parameters<typeof getModels>[0]); } catch { /* no local catalog */ }
		const models: GatewayModelConfig[] = [];
		const routes = new Map<string, string>();
		for (const id of provider.models ?? []) {
			const entry = fromServer?.models.find((m) => m.id === id);
			if (!entry) continue;
			const model = mergeModelMetadata(entry, { id }, cfg.overrides[id] ?? {}, api, entry.providerId ? undefined : catalog.find((m) => m.id === id));
			addRoute(name, entry, model.id, routes);
			models.push(model);
		}
		if (models.length) register(name, api, models, routes);
		else report.skipped.push({ provider: name, reason: "no whitelisted models present on proxy" });
	}

	const byId = new Map(discovery.customPool.map((m) => [m.id, m]));
	for (const [name, provider] of Object.entries(cfg.customProviders)) {
		if (!ALLOWED_APIS.has(provider.api)) {
			report.skipped.push({ provider: name, reason: `api "${provider.api}" not in allowlist` });
			continue;
		}
		const models: GatewayModelConfig[] = [];
		const routes = new Map<string, string>();
		for (const configured of provider.models) {
			const entry = byId.get(configured.id);
			if (!entry) continue;
			if (entry.api !== provider.api) throw new Error(`Model ${entry.id} requires ${entry.api}, not ${provider.api}`);
			const model = mergeModelMetadata(entry, configured, cfg.overrides[entry.id] ?? {}, provider.api);
			addRoute(name, entry, model.id, routes);
			models.push(model);
		}
		if (models.length) register(name, provider.api, models, routes);
		else report.skipped.push({ provider: name, reason: "no configured models present on proxy" });
	}
	for (const name of ownedNames) {
		if (!registeredNames.has(name)) pi.unregisterProvider(name);
	}
	appliedProviderNames.set(pi, registeredNames);
	log.info(`applyAll: registered ${report.registered.length} providers, skipped ${report.skipped.length}`);
	return report;
}

function addRoute(name: string, entry: DiscoveryModelEntry, selector: string, routes: Map<string, string>): void {
	const wireId = entry.wireId ?? entry.id;
	if (entry.providerId && (!wireId.includes("/") || !entry.selectorId || selector.includes("/"))) throw new Error(`Invalid gateway route: ${entry.id}`);
	if (routes.has(selector)) throw new Error(`Ambiguous selector ${name}/${selector}`);
	routes.set(selector, wireId);
}

/** Legacy display-oriented names are folded into safe provider slugs. */
export function registerAllSlug(suggested: string): string {
	const slug = suggested.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
	return slug || "pool";
}
